server:
  port: ${PORT:8080}
  host:

spring:
  datasource:
    password: ${PROD_POSTGRE_PASSWORD:123}
    username: ${PROD_POSTGRE_USERNAME:postgres}
    url: ${PROD_POSTGRE_URL:jdbc:postgresql://localhost:5432/}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
